Eng 1858
Basis-Theory/basis-theory-elements-interfaces pull request #64
Opened 2021-12-20 14:50 UTC by brigonzalez

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2021-12-20 20:25 UTC, lcschy approved these changes
yolo 💯

2021-12-21 18:15 UTC, djejaquino requested changes

2021-12-21 18:16 UTC, djejaquino submitted a review, later dismissed

2021-12-22 18:02 UTC, djejaquino approved these changes

2021-12-22 18:33 UTC, lcschy approved these changes

2021-12-22 18:37 UTC, merged

2021-12-22 18:38 UTC, bt-platform-eng commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@basis-theory/basis-theory-elements-interfaces/v/2.0.0)
- [GitHub release](https://github.com/Basis-Theory/basis-theory-elements-interfaces/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: