ENG-1915 - Add password to text element options
Basis-Theory/basis-theory-elements-interfaces pull request #79
Opened 2022-01-06 19:10 UTC by lcschy

## Description
- Adds `password` boolean as a customizable option.

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-01-06 20:21 UTC, djejaquino approved these changes

2022-01-06 20:21 UTC, djejaquino requested changes
Isn't that adding the option to the Card too?

2022-01-06 20:53 UTC, lcschy commented
> Isn't that adding the option to the Card too?

oops, fixed it.

2022-01-07 12:43 UTC, djejaquino approved these changes

2022-01-07 12:44 UTC, merged

2022-01-07 12:45 UTC, bt-platform-eng commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@basis-theory/basis-theory-elements-interfaces/v/2.2.0)
- [GitHub release](https://github.com/Basis-Theory/basis-theory-elements-interfaces/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: