feat: exposing new react endpoint
Basis-Theory/basis-theory-elements-interfaces pull request #95
Opened 2022-03-16 22:16 UTC by jleon15

## Description

- exposing new react endpoint

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2022-03-18 20:01 UTC, djejaquino requested changes

2022-03-18 20:01 UTC, djejaquino commented on src/sdk/services/shared.ts
>      id: string,
```suggestion
    tokenId: string,
```

2022-03-18 22:10 UTC, jleon15 commented on src/sdk/services/shared.ts
>      id: string,
where is this type used? i don't think it's used by the js sdk

2022-03-21 12:23 UTC, djejaquino requested changes

2022-03-21 12:23 UTC, djejaquino commented on src/sdk/services/reactors.ts
> +import { RequestOptions } from '.';
```suggestion
import { RequestOptions } from './shared';
```
Importing from same index where types / consts are also exported may lead to circular dependencies in some edge cases..

2022-03-21 12:23 UTC, djejaquino commented on src/sdk/services/shared.ts
>      id: string,
`AtomicBanks` and `AtomicCards` extend it.  `BasisTheory` class from the SDK implements `BasisTheory` interface, which has these services.
But the suggestion has to do with making clear to the users which `id` the should be targeting for when using this this endpoint, since now we have another one straight from `Reactors`

2022-03-21 17:57 UTC, djejaquino approved these changes

2022-03-21 18:12 UTC, merged

2022-03-21 18:13 UTC, bt-platform-eng commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@basis-theory/basis-theory-elements-interfaces/v/3.5.0)
- [GitHub release](https://github.com/Basis-Theory/basis-theory-elements-interfaces/releases/tag/v3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: